# Generated by Django 5.0.7 on 2024-07-13 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_file_category_alter_file_img_alter_file_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='img',
            field=models.FileField(default='app/static/app/static/img/doc.png', upload_to='app/static/fileimg'),
        ),
    ]
