# Generated by Django 5.0.7 on 2024-07-17 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_storage'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='size',
            field=models.ManyToManyField(to='app.storage'),
        ),
    ]
