# Generated by Django 5.0.7 on 2024-07-17 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_storage_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storage',
            name='user',
        ),
    ]
