# Generated by Django 5.0.7 on 2024-07-20 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_storage_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage',
            name='price',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
            preserve_default=False,
        ),
    ]
